name: 'Check Format and Generate ISO Image'
on:
  push:
  schedule:
  - cron: 15 14 * * *
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: ./.github/actions/restore-nix-cache
    - run: nix-shell -p nixpkgs-fmt --run 'nixpkgs-fmt --check .'
    - uses: ./.github/actions/save-nix-cache
  build-iso:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: ./.github/actions/restore-nix-cache
    - run: iso/geniso.sh
    - name: Check that image can fit on an 8GB USB flash drive
      run: |
        if ! find iso/result/iso -name *.iso -size -8000M | grep -q .; then
          echo "::warning title=Image too large!::ISO image may be too large to fit on an 8GB USB flash drive."
        fi
    - uses: actions/upload-artifact@v4
      with:
        name: iso-images
        path: iso/result/iso/*.iso
    - uses: ./.github/actions/save-nix-cache
