on:
  push:
  schedule:
  - cron: 15 14 * * *
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: ./.github/actions/restore-nix-cache
    - run: nix-shell -p nixpkgs-fmt --run 'nixpkgs-fmt --check .'
    - uses: ./.github/actions/save-nix-cache
  build-iso:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: ./.github/actions/restore-nix-cache
    - run: iso/geniso.sh
    - uses: actions/upload-artifact@v3
      with:
        name: iso-images
        path: iso/result/iso/*.iso
    - uses: ./.github/actions/save-nix-cache
