name: 'Check'

on:
  push:

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell -p nixpkgs-fmt --run 'nixpkgs-fmt --check .'
